### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by Shoegzer**

### CODE REVIEW

**Review by beaumanvienna — CHANGES_REQUESTED** [review]
This change looks really good and can soon be pulled in. :-)

"Maryley's system requirements.." --> Marley's

The changed section header needs to be updated in the table of contents. In Github markup, links to section headers are written in all lower-case letters and hyphens instead of spaces

**Comment by beaumanvienna** [comment]
Thank you for your contribution! My text was a bit too chatty :-)

**Comment by Shoegzer** [comment]
You bet!  Sometimes another pair of eyes can help.

**Comment by beaumanvienna** [comment]
_Marley runs [..], with Nvidia or AMD OpenGL graphics acceleration_

Should we also mention Intel?

**Comment by beaumanvienna** [comment]
The Mesa driver also supports Intel, tested on my old Acer V5 laptop

**Comment by beaumanvienna** [comment]
I added it really quickly

**Comment by Shoegzer** [comment]
Surprised I'd overlooked that myself but yes, that sounds good.

**Pull request merged**
